// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAcademy.Model
{
    [Table("tb_Cliente")]
    public partial class TbCliente
    {
        [Key]
        [Column("cli_Id")]
        public int CliId { get; set; }
        [Required]
        [Column("cli_Nome")]
        [StringLength(35)]
        [Unicode(false)]
        public string CliNome { get; set; }
        [Column("cli_DataNasc", TypeName = "date")]
        public DateTime CliDataNasc { get; set; }
        [Required]
        [Column("cli_CPF")]
        [StringLength(15)]
        [Unicode(false)]
        public string CliCpf { get; set; }
        [Required]
        [Column("cli_Email")]
        [StringLength(50)]
        [Unicode(false)]
        public string CliEmail { get; set; }
    }
}