// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAcademy.Model
{
    [Table("tb_Funcionario")]
    public partial class TbFuncionario
    {
        [Key]
        [Column("fun_Id")]
        [Display(Name="Código")] // Adicionado "Data Anotation"
        public int FunId { get; set; }
        [Required]
        [Column("fun_Nome")]
        [Display(Name = "Nome")]
        [StringLength(35)]
        [Unicode(false)]
        public string FunNome { get; set; }
        [Column("fun_DataNasc", TypeName = "date")]
        [Display(Name = "Data de Nascimento")]
        public DateTime FunDataNasc { get; set; }
        [Required]
        [Column("fun_CPF")]
        [Display(Name = "CPF")]
        [StringLength(15)]
        [Unicode(false)]
        public string FunCpf { get; set; }
        [Required]
        [Column("fun_Email")]
        [Display(Name = "Email")]
        [StringLength(50)]
        [Unicode(false)]
        public string FunEmail { get; set; }
        [Required]
        [Column("fun_Modalidade")]
        [Display(Name = "Modalidade")]
        [StringLength(15)]
        [Unicode(false)]
        public string FunModalidade { get; set; }
        [Required]
        [Column("fun_Categoria")]
        [Display(Name = "Categoria")]
        [StringLength(15)]
        [Unicode(false)]
        public string FunCategoria { get; set; }
    }
}