// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAcademy.Model
{
    [Table("tb_Treino")]
    public partial class TbTreino
    {
        [Key]
        [Column("tre_Id")]
        public int TreId { get; set; }
        [Column("tre_DataHora", TypeName = "datetime")]
        public DateTime TreDataHora { get; set; }
        [Column("tre_Modalidade")]
        [StringLength(10)]
        [Unicode(false)]
        public string TreModalidade { get; set; }
    }
}